### ISSUE TITLE
Release v545.0 has several breaking changes

### ISSUE THREAD

**Issue by the-gigi** [pulumi/pulumi-cloudflare#1010]
### Describe what happened

The release notes list the breaking changes, but there is no guidance on upgrading

https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.45.0

I wouldn't expect a minor version bump to introduce multiple undocumented breaking changes. Is it a carryover from terraform?

### Sample program

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @the-gigi -

As this provider is derived from https://github.com/cloudflare/terraform-provider-cloudflare, we follow their version bumps. 

Not all upstream providers are conscientious about semver conventions; however, in general, changes such as these, which are on resource fields (not missing entire resources) are considered acceptable as part of minor releases on all Pulumi providers. Terraform providers are the same.
Our [documentation](https://www.pulumi.com/registry/packages/cloudflare/) is updated accordingly. 
You can also refer to the [upstream changelog](https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v4.48.0) for additional information; however, you'll note there's no upgrade guide there either.

Is there a particular difficulty you're encountering with this version? We'd be happy to amend the release notes with any special challenges that you have needed to find solutions for. Thank you!

**Comment by the-gigi** [comment]
Hi @guineveresaenger,
Thanks for the info.
 
The difficulty is that as correctly specified in the release notes it contains breaking changes. So, in order to upgrade we will need to understand what's the meaning of these changes and how to updae our code to accommodate them without breaking our infra. Since, it's going to be a problem for every user that provisions one of the impacted resources I was hoping for centralized guidance. Regardless of the semever conventions, typically when introducing breaking changes to a popular package it is accompanied by some upgrade notes.

I totally understand you're an intermediary in this case and didn't explicitly modify anything. I guess I'll take it upstream.

**Comment by guineveresaenger** [comment]
Hi @the-gigi - since you're not currently experiencing specific trouble with this upgrade, I'm going to close the issue for now. Please feel free to re-open if we can assist with any particular concerns!
