### ISSUE TITLE
Unable to create CAA records

### ISSUE THREAD

**Issue by ydkn** [pulumi/pulumi-cloudflare#105]
Hi there,

I'm currently trying to set CAA records on Cloudflare. To do that I need to set the issuer, flags and tag. Sadly I can not figure out how to set the tag. The documentation only includes the property `keyTag` which is a number but the tag needs to be a string e.g. `issue`. Am I missing something or is there currently no option to actually set the `tag` property for the request which would make creating a CAA record impossible?

Here is an example as far as I think it should be correct without the `tag` property:

```typescript
const caaLetsEncrypt = new cloudflare.Record("caa-record", {
    zoneId,
    name: "@",
    type: "CAA",
    data: { flags: "0", content: "letsencrypt.org" },
});
```

Cheers,
Florian

**Comment by stack72** [comment]
Hi @ydkn 

Apologies for the issue here - I am trying to find what the API request to the Cloudflare API would look like for this so I can try and debug this and work it out

Paul

**Comment by stack72** [comment]
Hi

Just checking in here - I send the PR back upstream for this https://github.com/cloudflare/terraform-provider-cloudflare/pull/866

Paul
