### ISSUE TITLE
unable to install cloudfare resource 

### ISSUE THREAD

**Issue by koneru9999** [pulumi/pulumi-cloudflare#119]
I have following dependencies in our package json

```json
{
  
  "dependencies": {
     "@pulumi/aws": "2.12.0",
     "@pulumi/awsx": "0.20.0",
     "@pulumi/cloudflare": "2.6.0",
     "@pulumi/pulumi": "2.7.0"
  }
 
}
```
i got the following error when `pulumi up` is issued
```
Diagnostics:
  pulumi:providers:cloudflare (default_2_12_0):
    error: no resource plugin 'cloudflare-v2.12.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource cloudflare v2.12.0`
```

So i tried the above suggested command `pulumi plugin install resource cloudflare v2.12.0` but it threw `HTTP 403` error.

```
error: [resource plugin cloudflare-2.12.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-cloudflare-v2.12.0-darwin-amd64.tar.gz
```

I tried this command with several previous versions and the last version it seems to work is `v2.7.0`. 

I wonder if the plugin files are not pushed or made available to public.

Node version: v12.16.3
Pulumi CLI version: v2.13.0

**Comment by stack72** [comment]
Hey @koneru9999 

Sorry about this issue you are getting - I am not sure why this is and will need to look into it

The latest release of cloudflare is v2.7.0 so that message is incorrect to download v2.12.0

Paul

**Comment by koneru9999** [comment]
@stack72
I had the same concern initially and it seems the version seems to be getting from `@pulumi/aws` dependency. 
If i change my `@pulumi/aws` dependency to `2.11.0`, then it tries to install resource plugin 'cloudflare-v2.11.0'

Hope this helps in troubleshooting.

**Comment by agonbina** [comment]
@stack72 so is this going to be looked at anytime soon? We had to downgrade our `@pulumi/aws` plugin so that we can use it with this plugin, which introduced other issues into our stack. 

We would appreciate it if you can let us know whether there is any plans to resolve this issue or if we should remove it from our implementation. Thanks.

**Comment by leezen** [comment]
Trying this with the latest version of the CLI and the above mentioned package versions, I'm unable to reproduce this. I also cannot reproduce this with the latest versions of `@pulumi/aws` and `@pulumi/cloudflare`

Happy to re-open and take a look if anyone is able to provide a reliable repro.
