### ISSUE TITLE
support "AMP Real URL"

### ISSUE THREAD

**Issue by thanhtoan1196** [pulumi/pulumi-cloudflare#137]
AMP Real URL
Display your site’s actual URL on your AMP pages, instead of the traditional Google AMP cache URL

Navigation: Speed > Optimization > Mobile > AMP Real URL

**Comment by stack72** [comment]
Hi @thanhtoan1196 

Thanks for opening this issue - please can you link me to the API functionality that supports this? I can't see to find it :/

Paul

**Comment by thanhtoan1196** [comment]
@stack72 Well, it looks like there is no api for this function
I will close the issue.

**Comment by stack72** [comment]
Ah I'm really sorry about that @thanhtoan1196 :/
