### ISSUE TITLE
Record: invalid or unknown key: zone_id

### ISSUE THREAD

**Issue by mgranderath** [pulumi/pulumi-cloudflare#143]
I was just trying to redeploy a project of mine that utilizes this for creating/updating the DNS records on cloudflare. For some reason it seems to fail with the following error: 

```
 cloudflare:index:Record (staging-main):
    error: could not validate provider configuration: 1 error occurred:
        * : invalid or unknown key: zone_id
````

I already updated all pulumi dependencies to the newest versions.

## Expected behavior
The DNS records should be updated or created

## Current behavior

For the following code:

```typescript
new cloudflare.Record(
  getDeploymentName(deploymentType, "main"),
  {
    name: deploymentType == DeploymentType.PRODUCTION ? `www.${baseHostname}` : baseHostname,
    type: "CNAME",
    value: input.networking.listener.endpoint.hostname,
    proxied: true,
    zoneId: zoneId,
  },
  defaultResourceOptions
);
```

Pulumi fails with the error:

```
 cloudflare:index:Record (staging-main):
    error: could not validate provider configuration: 1 error occurred:
        * : invalid or unknown key: zone_id
```

## Context (Environment)
I currently can't deploy without disabling the cloudflare plugin.

Current dependencies
```json
"dependencies": {
    "@pulumi/aws": "^2.0.0",
    "@pulumi/awsx": "^0.20.0",
    "@pulumi/cloudflare": "^2.5.0",
    "@pulumi/docker": "^2.2.3",
    "@pulumi/pulumi": "^2.0.0",
    "firebase-tools": "^8.10.0",
    "node-fetch": "^2.6.0"
}
```

## Affected feature
I already checked on the terraform cloudflare github if someone opened an issue there but it does not seem like it. I'm not entirely sure where this issue could be coming from since I hadn't changed anything since the last deploy.

**Comment by mgranderath** [comment]
@stack72 sorry for the mention but this is hindering me from deploying critical fixes to production right now. I've tried to find the issue for several hours but I have no idea where to continue. I'd really appreciate any help and thank you for all of the work on this!

**Comment by mgranderath** [comment]
Nevermind; Apparently a mistake on my side that came from an update of pulumi. For anyone that is encountering the same issue in future. Make sure that the config namespace does not have the same name as the provider. In my case I had a config key `cloudflare:zoneId` and that caused the issue. Renaming to `cloudflare-config:zoneId` solved the problem.

**Comment by maZahaca** [comment]
@mgranderath you've just saved another 3 hours of my life 🤣
