### ISSUE TITLE
[Feature] Create CAA Records programmatically

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi-cloudflare#157]
I was running into [problems](https://docs.aws.amazon.com/acm/latest/userguide/setup-caa.html) when creating ACM Certificates, and the solution was to create CAA Records. I'd love to be able to create these programmatically as part of my pulumi codebase.

**Comment by stack72** [comment]
Hi @gunar 

I believe I added this functionality as part of v2.9.0 of pulumi-cloudflare

Do you not seen the ability to do this?

Paul

**Comment by gunar** [comment]
Hey @stack72, well I can't find any docs nor source code pointing to the "CAA" record type. Maybe I'm missing something?

**Comment by stack72** [comment]
A CAA record is just another type of Record in Pulumi. I know the following works here:

```
import * as pulumi from "@pulumi/pulumi";
import * as cloudflare from "@pulumi/cloudflare";

const sampleCaa = new cloudflare.Record("sampleCaa", {
    data: {
        flags: "0",
        tag: "issue",
        value: "letsencrypt.org",
    },
    name: "mydomain.com",
    ttl: 600,
    type: "CAA",
    zoneId: "mydomain.com",
});
```

We are inheriting the lack of examples from the upstream provider here :/

**Comment by gunar** [comment]
Oh I hadn't realized there was a `data` field. The snipped above works! (but I had to remove the key `name`)

Thank you so much @stack72 — you're awesome!
