### ISSUE TITLE
Unmarshalling error in cloudflare client when creating a CertifcatePack 

### ISSUE THREAD

**Issue by bruno-morel** [pulumi/pulumi-cloudflare#167]
It worked 3 days ago, now it doesnt...

I I try to create a CertificatePack from pulumi, here is what I get:
`failed to fetch certificate pack: error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field CertificatePack.result.primary_certificate of type int`

## Steps to reproduce
1. Create a Certificate Pack using https://www.pulumi.com/docs/reference/pkg/cloudflare/certificatepack/
2. We use the advanced type, for an active zone using digicert
3. Watch it fail after having created the pack in CloudFlare (so it does create it, but fail after)

Expected: no failure
Actual: full failure of the update + impossible to rely on the created object in subsequent flow

**Comment by tricky42** [comment]
I ran into the same problem. When refreshing our Pulumi stack we get the same error:

```
error: refreshing urn:pulumi:staging::loadbalancer::cloudflare:index/certificatePack:CertificatePack::certPack_staging_domain: failed to fetch certificate pack: error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field CertificatePack.result.primary_certificate of type int
```

**Comment by tricky42** [comment]
@stack72 Can you provide any update on this issue. I would be willing help fixing the issue, but I think I need some pointers to get started what introduced the issue in the first place.

**Comment by tricky42** [comment]
Here is the related issue in the Cloudflare Terraform Provider:
- https://github.com/cloudflare/terraform-provider-cloudflare/issues/1139

This issue has been closed and I see that in the last release of the Cloudflare Terraform Provider this has been fixed: 
- https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v2.25.0
- with the version update of cloudflare-go to v0.20.0: https://github.com/cloudflare/terraform-provider-cloudflare/pull/1146

I can see you updated to v.2.25.0 before releasing v3.4.0, but I am still getting the error although I ensured I am using v3.4.0: `"@pulumi/cloudflare": "3.4.0"`.

Any tip how I can resolve the issue @stack72?

**Comment by tricky42** [comment]
I further looked into this and found a workaround for our setup.

In our scripts we are first running `pulumi refresh` before `pulumi up` and the error happened during the refresh. I first ensured that I am using the latest version of Pulumi / Pulumi Cloudflare Provider (you can check the plugin version by calling `pulumi plugin ls`). 

Then I temporarily disabled the `pulumi refresh` call and just ran `pulumi up`, which completed without problems. I think this updated the stored state (we are using Pulumi Cloud) and now I was able to enable `pulumi refresh` again, which now runs without problems.

**Comment by bruno-morel** [comment]
It looks like it's working, I have a bunch of service to check, but the first one was happy with it. I'll keep you updated if I encounter more trouble, but thanks for finding a working fix!

**Comment by mikhailshilkov** [comment]
The upstream issue has been fixed and nobody commented on this issue since 2021, so I'll go ahead and close it as fixed
