### ISSUE TITLE
Unable to set steeringPolicy to "proximity"

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi-cloudflare#195]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have upgraded the Cloudflare provider to v3.5.0 to set the `steeringPolicy` of a `LoadBalancer` to `proximity` but get the below error:

````error: cloudflare:index/loadBalancer:LoadBalancer resource 'id-srv-load-balancer' has a problem: expected steering_policy to be one of [off geo dynamic_latency random ], got proximity````

Version 3.5.0 of the Cloudflare Pulkumi provider is based on the Terraform Provider `v2.26.1`. Support for `proximity` as a value was released in `v2.21.0` (https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#2210-may-26th-2021), so I would have expected this to work.

I am using the Automation API and have correctly called `await ws.installPlugin('cloudflare', 'v3.5.0')` to ensure the correct plugin is installed.

Am I missing something?

### Steps to reproduce

Create a load balancer:

````ts
            new cloudflare.LoadBalancer('app-load-balancer', {
                zoneId: 'the-zone-id',

                fallbackPoolId: allPools[0],
                defaultPoolIds: allPools,

                enabled: true,

                name: pulumi.interpolate`app.${cloudflareGlobalExports.cloudflareEndpointsZoneName}`,

                steeringPolicy: 'proximity',

                proxied: true,

                sessionAffinity: 'none',
            });
````

**Comment by leezen** [comment]
In addition to the plugin version, the other thing I would check here is if somehow the `@pulumi/cloudflare` SDK version is somehow an older version (and it in turn is using the older version of the plugin that is somehow in the path?)

**Comment by barclayadam** [comment]
Hi @leezen. I have confirmed that the npm package is correct and is using v3.5.0. I am reluctant to try any furthers versions as upgrading to v4 as a test led to DNS records being recreated (or at leats, attempts were made to recreate instead of maintain existing).

**Comment by leezen** [comment]
@barclayadam Sorry for not digging in further at the onset. I took at a look at the code in `v2.26.1` and you can see that `proximity` for steering policy only applies as a rule, but not for the top-level `steering_policy` property: https://github.com/cloudflare/terraform-provider-cloudflare/blob/v2.26.1/cloudflare/resource_cloudflare_load_balancer.go#L93

This is corrected in `v2.27.0`: https://github.com/cloudflare/terraform-provider-cloudflare/blob/v2.27.0/cloudflare/resource_cloudflare_load_balancer.go#L93

Unfortunately, that upstream version was never brought in prior to moving to the underlying upstream v3 provider version.

**Comment by stack72** [comment]
Hi @barclayadam (and @leezen)

I have just created a new tag based on the v2.27.0 release of the TF provider and our v3.5.0 - it has been tagged as v3.6.0 and is going through our build process now

I expect this will be ready in about 45 mins or so. I will post back when it's ready

Paul

**Comment by stack72** [comment]
ok, v3.6.0 release is out there and should solve the issue - please let us know @barclayadam

**Comment by barclayadam** [comment]
Hi @stack72. Thank you for the quick turnaround yesterday and for getting that released. I had not spotted the difference in rule vs top-level either.

I can confirm that 3.6.0 worked perfectly for this.

**Comment by stack72** [comment]
Thanks for confirming all is good here  @barclayadam - we will make sure and update our process to make these provider releases better
