### ISSUE TITLE
Update PageRule docs regarding zone name

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-cloudflare#24]
As seen in https://github.com/pulumi/pulumi-cloudflare/issues/23, it's unclear that zone for `PageRule` is actually the zone name (e.g. `example.com`) and not the zone id.

We should update the docs (or alternatively the property name) to be more clear.

**Comment by lukehoban** [comment]
This package is automatically derived from https://github.com/terraform-providers/terraform-provider-cloudflare, so I don't think it would be a good idea to change the property names in our layer - possibly worth suggesting that in the upstream provider - though would be a breaking change there (and here).

**Comment by stack72** [comment]
I personally think the documentation needs to be better here - I will submit a fix upstream that makes it more clear that it's the zone name not the ID

**Comment by stack72** [comment]
Hi folks, I am going to close this out. It seems there is a change coming down the pipeline that deprecates the use of zone in favour of zone_id

https://github.com/terraform-providers/terraform-provider-cloudflare/pull/421

This will hit soon I believe and will be able to be more explicit about which to use
