### ISSUE TITLE
Quick fix: expected DNS record to not already be present but already exists

### ISSUE THREAD

**Issue by thanhtoan1196** [pulumi/pulumi-cloudflare#241]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

How can I quickly fix this without having to manually delete the record and recreate it with pulumi
```
  cloudflare:index:Record (my-verification):
    error: 1 error occurred:
        * expected DNS record to not already be present but already exists
```

**Comment by guineveresaenger** [comment]
Hi @thanhtoan1196 - you should be able to import existing infrastucture into your Pulumi Stack.

More information on `pulumi import`: https://www.pulumi.com/docs/guides/adopting/import/ - and you should find the instructions specific to the Record resource here: https://www.pulumi.com/registry/packages/cloudflare/api-docs/record/#import

Feel free to drop by [our community slack](https://slack.pulumi.com/), for our community and asking questions as well.
