### ISSUE TITLE
Zero Trust Team Lists API pagination/limit issue

### ISSUE THREAD

**Issue by mrefish** [pulumi/pulumi-cloudflare#252]
### What happened?

I’m trying to use [Pulumi’s Cloudflare API for TeamsList](https://www.pulumi.com/registry/packages/cloudflare/api-docs/teamslist/) to manage the contents of my Gateway/Teams/Zero Trust Lists. I have a list with 144 items and when I import the list, Pulumi only found part of the list. This seems like it could be an issue with pagination and inconsistent behavior between the server and clients. Recreating the List with new code properly created the list, but the state is inconsistent and believes more entries need to be added.

### Steps to reproduce

- Create a list in the Cloudflare console with greater than 50 items (mine were 144 serial numbers)
- Import the list https://www.pulumi.com/registry/packages/cloudflare/api-docs/teamslist/#import
- The code reported by `pulumi import` is not complete

Alternatively
- Create a list with Pulumi's example usage with more than 50 items (again, I used 144 serial number)
- Run `pulumi up`
- List is created as expected
- Run `pulumi preview --diff` to see the Pulumi state is incorrect

### Expected Behavior

- Cloudflare TeamsList match between code, Cloudflare Console UI, and Pulumi State.
- `pulumi import` reports the full contents of the list in output of code
- `pulumi preview --diff` or `pulumi up` report no changes if no code changes were made.

### Actual Behavior

Pulumi state seems to only know about part of the list

### Versions used

Python [pulumi-cloudflare 4.6.0](https://pypi.org/project/pulumi-cloudflare/)

### Additional context

Topic on Cloudflare Community:
https://community.cloudflare.com/t/zero-trust-team-lists-api-pagination-issue-with-pulumi/384481

To see how the API was operating, I issued a few requests documented below

This returns 50 items and no information about pagination:

```
curl -X GET "https://api.cloudflare.com/client/v4/accounts/<ACCOUNT>/gateway/lists/<ID>/items" \
     -H "Authorization: bearer <TOKEN>" \
     -H "Content-Type: application/json"
```

Following the documentation on [Pagination](https://api.cloudflare.com/#getting-started-requests) the above request should have been roughly equivalent to this. Incrementing the page did not return different results.
```
curl -X GET "https://api.cloudflare.com/client/v4/accounts/<ACCOUNT>/gateway/lists/<ID>/items?page=1&per_page=50" \
     -H "Authorization: bearer <TOKEN>" \
     -H "Content-Type: application/json"
```

Only this returned the whole list by upping the limit above the list size (I found this query param in the developer tools while navigating the list in the console)
```
curl -X GET "https://api.cloudflare.com/client/v4/accounts/<ACCOUNT>/gateway/lists/<ID>/items?limit=1000" \
     -H "Authorization: bearer <TOKEN>" \
     -H "Content-Type: application/json"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @mrefish - thank you for reporting.

This is an [upstream issue in the Cloudflare API client](https://github.com/cloudflare/cloudflare-go/pull/897) that we are [inheriting from the Terraform provider](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1422).
