### ISSUE TITLE
Support for Cloudflare Pages

### ISSUE THREAD

**Issue by marcus-sa** [pulumi/pulumi-cloudflare#255]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd love to see support for [Cloudflare Pages](https://pages.cloudflare.com/)

**Comment by stack72** [comment]
Hi @marcus-sa 

Thanks so much for the request here - this is being tracked upstream - when they get it, we will get it :)

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1037

Paul
