### ISSUE TITLE
Failed to get smart routing setting: HTTP status 401: Not entitled to access this setting: smart_routing

### ISSUE THREAD

**Issue by thanhtoan1196** [pulumi/pulumi-cloudflare#261]
### What happened?

I just want to use the `tieredCaching` feature, but getting this error
```
failed to get smart routing setting: HTTP status 401: Not entitled to access this setting: smart_routing
```

### Steps to reproduce

Create Argo to enable `tieredCaching` like this:
```
new cloudflare.Argo(`argo`, {
                tieredCaching: "on",
                zoneId: app.zoneId,
            });
```

### Expected Behavior

`TieredCaching` can be enabled

### Actual Behavior

This error occurred:
```
  cloudflare:index:Argo (argo):
    error: 1 error occurred:
        * updating urn:pulumi:prod::main::cloudflare:index/argo:Argo::argo: 1 error occurred:
        * failed to get smart routing setting: HTTP status 401: Not entitled to access this setting: smart_routing (1015)

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
It looks like this issue was addressed upstream here: https://github.com/cloudflare/terraform-provider-cloudflare/pull/1451 
Can you report back if you are still running into this with the most current version of pulumi-cloudflare?

**Comment by thanhtoan1196** [comment]
OK, let me upgrade to the most current version of pulumi-cloudflare
