### ISSUE TITLE
Add support to latest Cloudflare Tunnels version

### ISSUE THREAD

**Issue by aczajkowski** [pulumi/pulumi-cloudflare#262]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi Provider supports currently only Argo Tunnel which is an older version of tunnels.
https://www.pulumi.com/registry/packages/cloudflare/api-docs/argotunnel/
We are using Pulumi for our IaaS and would like to include latest tunnel creation to our stacks. https://api.cloudflare.com/#cloudflare-tunnel-properties . 
New tunnels provide remote configuration support which is a crucial feature for us.
Is there a chance to extend provider to support it. 

### Affected area/feature

This will affect Pulumi SDK and Terraform bridge i suposse

**Comment by jkisk** [comment]
I looked into this and there are currently improvements in this area coming into the upstream provider, which we will make available as we pick up those releases.  I'm unsure if the exact features you are looking for are in the next release, but you can see some very recent progress here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1602

**Comment by vavsab** [comment]
> I looked into this and there are currently improvements in this area coming into the upstream provider, which we will make available as we pick up those releases. I'm unsure if the exact features you are looking for are in the next release, but you can see some very recent progress here: [cloudflare/terraform-provider-cloudflare#1602](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1602)

@jkisk I'm afraid that these changes are not related. Virtual networks and tunnels are different features. They are connected but still different.

**Comment by aczajkowski** [comment]
@jkisk thank you for information seems new features are slowly getting covered. 
But unfortunately @vavsab is right. In our case we need support for tunnels providing ingress traffic connections. 
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
Which are covered by this Cloudflare V4 API endpoints
https://api.cloudflare.com/#cloudflare-tunnel-properties 
https://api.cloudflare.com/#cloudflare-tunnel-configuration-properties

**Comment by jkisk** [comment]
I would encourage you to open issues or contribute via PR to the cloudflare/terraform-provider-cloudflare repo to register your interest in those properties.  It's true the process can be slow to wait for upstream open source contributions, which is why we encourage the use and authoring of our automatically generated [native providers](https://www.pulumi.com/blog/pulumiup-native-providers/) where possible.  Registering customer interest definitely helps though!

**Comment by aczajkowski** [comment]
@jkisk We already talk to CF :)

**Comment by aczajkowski** [comment]
@jkisk just an update. After meeting with CF we gained feedback that
https://www.pulumi.com/registry/packages/cloudflare/api-docs/argotunnel/
is compatible with latest cfd_tunnel which in not yet available as a separate resource in Terraform Provider.

So it's only this part which is missing CF Terraform Provider
https://api.cloudflare.com/#cloudflare-tunnel-configuration-properties

Thank you for your support.
