### ISSUE TITLE
Underlying error message not shown

### ISSUE THREAD

**Issue by renannprado** [pulumi/pulumi-cloudflare#275]
### What happened?

Error message is not fully exposed to the automation, therefore it's a bit more difficult to understand what's wrong.

```
Diagnostics:
  pulumi:pulumi:Stack (cloudflare-provisioning-prod-cloudflare-provisioning):
    error: update failed
 
  cloudflare:index:PageRule (example-com.pagerule-8):
    error: 1 error occurred:
    	* failed to create page rule: HTTP status 400: Page Rule validation failed: See messages for details. (1004)
ate page rule: HTTP status 400: Page Rule validation failed: See messages for details. (1004)
```

### Steps to reproduce

```typescript
new cloudflare.PageRule("pagerule1", {
    priority: 1,
    zoneId: "123",
    actions: {
        forwardingUrl: {
            statusCode: 302,
            url: "https://example.com",
        },
    },
    target: "http://example.com/*",
});


new cloudflare.PageRule("pagerule2", {
    priority: 2,
    zoneId: "123",
    actions: {
        forwardingUrl: {
            statusCode: 302,
            url: "https://example.com",
        },
    },
    target: "http://example.com/*",
});
```

### Expected Behavior

The error message shown should also carry the reason why it was not possible to create the pagerule (or any other resource), which in this case is the fact that there are multiple page rules matching exact the same thing.

This error is shown in Cloudflare's dashboard while you try to create such setup, so I believe the error is also available as part of the API, it's just not shown here.

In this case it would be something like this:

> .distinctTargetUrl: Your zone already has an existing page rule with that URL. If you are modifying only page rule settings use the Edit Page Rule option instead

### Actual Behavior

Underlying error message not shown.

### Versions used

```
CLI          
Version      3.36.0
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.38.1
cloudflare  4.6.0
nodejs      unknown
tls         4.3.0

Host     
OS       debian
Version  11.3
Arch     x86_64

This project is written in nodejs: executable='/home/user/.asdf/shims/node' version='v16.10.0'

Backend        
Name           user
URL            [redacted]
User           user
Organizations  

Dependencies:
NAME                                   VERSION
@pulumi/cloudflare                     v4.6.0
@typescript-eslint/eslint-plugin       5.28.0
@types/node                            17.0.27
eslint-plugin-prettier                 4.0.0
prettier                               2.7.0
typescript                             4.7.3
@pulumi/aws                            v4.38.1
@pulumi/tls                            v4.3.0
eslint-config-prettier                 8.5.0
eslint                                 8.17.0
@pulumi/pulumi                         3.30.0
axios                                  0.27.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Unfortunately this is a bug with the underlying terraform provider we bridge - tracked here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1579
