### ISSUE TITLE
Failed to create DNS record: DNS Validation Error (1004)

### ISSUE THREAD

**Issue by roger-5899** [pulumi/pulumi-cloudflare#292]
### What happened?

I'm getting a somewhat cryptic error:
`* failed to create DNS record: DNS Validation Error (1004)`

### Steps to reproduce

```typescript
const myZone = new cloudflare.Zone('example.com', {
  accountId: cfAccountId,
  zone: 'example.com',
});

new cloudflare.Record('foo-example', {
  zoneId: myZone.id,
  name: '_12345.foo',
  value: '_12345.bkngfjypgb.acm-validations.aws.',
  type: 'CNAME',
  ttl: 604800,
});
```

### Expected Behavior

Record should be created or better error message be shown.

### Actual Behavior

Cryptic error is displayed.

### Output of `pulumi about`

```
CLI          
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @roger-5899 - I'm fairly certain this is an error coming directly from Cloudflare: https://community.cloudflare.com/t/community-tip-fixing-code-1004-dns-validation-error/46697

I'm not at all familiar with Cloudflare, so apologies if this makes no sense, but I'm fairly certain your CNAME is not allowed to start with an underscore `_` character: https://developers.cloudflare.com/dns/manage-dns-records/reference/dns-record-types/#cname

Hope this helps!

**Comment by gunar** [comment]
You'll get the same error message when passing the wrong `type`. For example, using `CNAME` instead of `A` when you're passing an IP address into `value`.
