### ISSUE TITLE
`v4.13.0` no longer accepts API token from env var? 

### ISSUE THREAD

**Issue by dotansimha** [pulumi/pulumi-cloudflare#306]
### What happened?

Since `4.13.0`, it seems like this provided no longer respects `CLOUDFLARE_API_TOKEN` env var, and throws the following error when trying to `up`: 

```
    error: could not validate provider configuration: 3 errors occurred:
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
```

Downgrading to `4.12.1` seems to resolve this issue. 

### Steps to reproduce

1. Create a project and a stack, without configuring CloudFlare provider through Pulumi config. 
2. Set `CLOUDFLARE_API_TOKEN` as env var and run pulumi up.

### Expected Behavior

Should respect `CLOUDFLARE_API_TOKEN` and use it, when available.

### Actual Behavior

Error regarding a missing token.

### Output of `pulumi about`

```
CLI          
Version      3.48.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME        VERSION
cloudflare  4.12.1
nodejs      unknown

Host     
OS       darwin
Version  12.6
Arch     arm64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ombre9** [comment]
We are facing the same issue, is there any update?

**Comment by dotansimha** [comment]
@roothorp any update on this one? it's becoming a blocker for updating

**Comment by roothorp** [comment]
Hi @dotansimha and @ombre9 - we're currently examining this issue, and I'll comment here with any updates from the team. Thanks!

**Comment by jeremykerr** [comment]
Not sure if it helps, but seeing a similar issue with the terraform cloudflare provider. This is built on that, right?

- https://github.com/cloudflare/terraform-provider-cloudflare/issues/1919
- https://github.com/pulumi/pulumi-cloudflare/commits/master/provider/resources.go

**Comment by guineveresaenger** [comment]
@jeremykerr - that error message is a bit of a red herring.

It is [explicitly expected behavior](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#api_user_service_key) that this provider only accepts exactly one of those three inputs.

**Comment by guineveresaenger** [comment]
@dotansimha @ombre9 - we have included the tooling fix in the [latest release](This particular issue was cause by the bug in our tooling linked above. We have included this change in our [latest release](https://github.com/pulumi/pulumi-cloudflare/releases/tag/v4.14.0) which is building as I type and hope that it addresses your trouble!
