### ISSUE TITLE
Updating `PagesProject` source repository in-place is not possible, but no replace is performed

### ISSUE THREAD

**Issue by denisw** [pulumi/pulumi-cloudflare#320]
### What happened?

I have a Pulumi-managed `PagesProject` with `source.type == "github"`. I changed `source.config.owner` and this is recognized as an update by `pulumi preview` / `pulumi up`, but after running those, the source repository didn't actually change on the Cloudflare side.

Looking at the same Pages project in the Cloudflare dashboard, there is no option to change the source repository either, which strongly suggests to me that this is impossible to change in-place. The provider should thus do a replace instead of an update.

### Steps to reproduce

1. Deploy a `PagesProject` with `source.type == "github"`.
2. Change `source.config.owner` or `source.config.repoName` and run `pulumi up`.

### Expected Behavior

* The preview shows a replace (as an in-place update is possible).
* The (re-created) Pages project points to the new source repository.

### Actual Behavior

* The preview shows an in-place update (although it is not possible).
* Nothing has changed after `pulumi up` finishes.
* When running `pulumi up` again, it attempts to do the same impossible in-place update another time.

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME        VERSION
auth0       2.14.0
cloudflare  4.15.0
nodejs      unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.12.1'

Current Stack: dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::example::pulumi:pulumi:Stack::example-dev
pulumi:providers:cloudflare                 urn:pulumi:dev::example::pulumi:providers:cloudflare::default_4_15_0
pulumi:providers:auth0                      urn:pulumi:dev::example::pulumi:providers:auth0::default_2_14_0
auth0:index/client:Client                   urn:pulumi:dev::example::auth0:index/client:Client::auth0-client
auth0:index/resourceServer:ResourceServer   urn:pulumi:dev::example::auth0:index/resourceServer:ResourceServer::auth0-api
auth0:index/tenant:Tenant                   urn:pulumi:dev::example::auth0:index/tenant:Tenant::auth0-tenant
auth0:index/clientGrant:ClientGrant         urn:pulumi:dev::example::auth0:index/clientGrant:ClientGrant::auth0-client-management-api-grant
auth0:index/connection:Connection           urn:pulumi:dev::example::auth0:index/connection:Connection::auth0-passwordless-email
auth0:index/role:Role                       urn:pulumi:dev::example::auth0:index/role:Role::auth0-submitter-role
auth0:index/role:Role                       urn:pulumi:dev::example::auth0:index/role:Role::auth0-reviewer-role
cloudflare:index/pagesProject:PagesProject  urn:pulumi:dev::example::cloudflare:index/pagesProject:PagesProject::cloudflare-pages-components
cloudflare:index/pagesProject:PagesProject  urn:pulumi:dev::example::cloudflare:index/pagesProject:PagesProject::cloudflare-pages-spec
auth0:index/client:Client                   urn:pulumi:dev::example::auth0:index/client:Client::auth0-automation-client


Found no pending operations associated with dev

Backend        
Name           Deniss-MacBook-Pro.fritz.box
URL            s3://pulumi?endpoint=fe43443d552eccfb1a94b1b6dfd66832.r2.cloudflarestorage.com&s3ForcePathStyle=true
User           denis.washington@futurice.com
Organizations  

Dependencies:
NAME                              VERSION
eslint                            8.30.0
@typescript-eslint/eslint-plugin  5.47.0
@typescript-eslint/parser         5.47.0
eslint-plugin-import              2.26.0
husky                             8.0.3
@pulumi/auth0                     2.14.0
@pulumi/cloudflare                4.15.0
@pulumi/pulumi                    3.48.0
@types/node                       14.18.34
prettier                          2.8.1

Pulumi locates its logs in /var/folders/hf/x89std3j1tsc_nbc6mhf0hm80000gp/T/ by default
```

### Additional context

This might be an upstream issue with the Terraform Cloudflare provider, which I didn't test directly. I found no comparable bug report there.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks for reporting this! Terraform allows encoding that a resource property change would require replacing the resource, however this has not been done for the PagesProject as far as I can tell from the links below:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/20222d155d457736d71eaa41a63bb87853cfaf29/internal/provider/schema_cloudflare_pages_project.go#L53-#L53
https://github.com/pulumi/terraform-provider-cloudflare/blob/b5da5489458fe4c2158224c19a5653f268b0cb33/internal/provider/schema_cloudflare_pages_project.go#L52-#L52

In this case the best way to get this fixed is to get github.com/cloudflare/terraform-provider-cloudflare to accept a change marking the properties as requiring replacement, and then bring pulumi/pulumi-cloudflare up-to-date with the latest version of upstream.

**Comment by mjeffryes** [comment]
This field is now properly flagged to trigger a replace
