### ISSUE TITLE
ManagedHeaders local/remote state always mismatch

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi-cloudflare#341]
### What happened?

```python
cloudflare.ManagedHeaders('example',
    zone_id=zone.id,
    managed_request_headers=[
        cloudflare.ManagedHeadersManagedRequestHeaderArgs(id='add_true_client_ip_headers', enabled=False),
        cloudflare.ManagedHeadersManagedRequestHeaderArgs(id='remove_visitor_ip_headers', enabled=False),
    ],
    managed_response_headers=[
        cloudflare.ManagedHeadersManagedResponseHeaderArgs(id="remove_x-powered-by_header", enabled=False),
        cloudflare.ManagedHeadersManagedResponseHeaderArgs(id="add_security_headers", enabled=False),
    ],
)
```

`pulumi up` and `pulumi refresh` always show that there is a change to be applied to this resource. It seems that terraform provider only read enabled headers, causing troubles for pulumi to compare local & remote state. See https://github.com/cloudflare/terraform-provider-cloudflare/blob/d2370deffbab5cced739ba5868815524dd1ac668/internal/sdkv2provider/resource_cloudflare_managed_headers.go#L37-L43.

### Expected Behavior

local/remote state should match after a successful `pulumi up`

### Steps to reproduce

Prepare a ManagedHeadersManagedRequestHeaderArgs or ManagedHeadersManagedResponseHeaderArgs with enabled=False.

### Output of `pulumi about`

CLI
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
alicloud    3.30.0
cloudflare  4.15.0
python      unknown

Host
OS       darwin
Version  13.2
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.10.10'

Current Stack: prod

[truncated]

Dependencies:
NAME               VERSION
pip                23.0.0
pulumi-cloudflare  4.15.0
setuptools         67.2.0
wheel              0.38.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@zhangyoufu Thanks for reporting this, but I'm a little confused at why one would set headers to `enabled=False` instead of removing them from the list of managed headers.

**Comment by zhangyoufu** [comment]
> Could you elaborate on the use case for setting them to disabled instead of removing them?

I feel like to be verbose and list all available configuration.

It would be convenient when I copy-paste it for another resource and want to change one or two settings. I don't have to look up provider document and Cloudflare dashboard to figure out which property should I change.

Cloudflare dashboard and its API organize available settings in different ways, and I feel time-consuming to pinpoint which input of which resource corresponds to which setting on the dashboard.

I am aware that I can remove them instead of listing with `enabled=False` to workaround this issue.

I didn't test this resource against Terraform. But by reading the code under `buildManagedHeadersListFromResource`, I think this issue only affects Pulumi. It's not an upstream issue. That's why I reported here.

**Comment by AaronFriel** [comment]
Thanks, it makes sense that if `enabled` is a property you'd like to manage it with Pulumi.

It does look like this is an upstream issue, this request here looks like it filters out header items that aren't enabled.

https://github.com/cloudflare/terraform-provider-cloudflare/blob/d2370deffbab5cced739ba5868815524dd1ac668/internal/sdkv2provider/resource_cloudflare_managed_headers.go#L41-L43

**Comment by zhangyoufu** [comment]
> this request here looks like it filters out header items that aren't enabled.

Yes. I understand that `resourceCloudflareManagedHeadersRead` filters out header items that aren't enabled.

The symmetric part in `buildManagedHeadersListFromResource` also filters out header items that aren't enabled for local resource. So Terraform only compares enabled items between local resource and remote state. This part is exactly what pulumi-cloudflare provider is missing.

**Comment by AaronFriel** [comment]
The update method eventually calls `buildManagedHeadersListFromResource`, so I believe Pulumi's behavior here is symmetric if and only if the upstream provider is. If we're behaving differently, I'd be surprised and I'd appreciate a snippet to reproduce.

https://github.com/cloudflare/terraform-provider-cloudflare/blob/d2370deffbab5cced739ba5868815524dd1ac668/internal/sdkv2provider/resource_cloudflare_managed_headers.go#L74-L92

Given that this appears to be an upstream issue for which a workaround exists, so I'm going to relabel this issue to "kind/enhancement".

**Comment by zhangyoufu** [comment]
Sorry, this is exactly the behavior of upstream Terraform provider.

By the way, I found that [upstream document](https://registry.terraform.io/providers/cloudflare/cloudflare/3.35.0/docs/resources/zone_settings_override) warned about this verbose style. (though that warning shows on `cloudflare_zone_settings_override` instead of `cloudflare_managed_headers`)

> You should not use this resource to manage every zone setting. This resource is only intended to override those which you do not want the default. Attempting to manage all settings will result in problems with the resource applying in a consistent manner.
