### ISSUE TITLE
breaking change in v5 - ArgoTunnel changed to Tunnel

### ISSUE THREAD

**Issue by omercnet** [pulumi/pulumi-cloudflare#365]
### What happened?

trying to upgrade to v5 broke the build as ArgoTunnel was renamed to Tunnel

see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade for other breaking changes

### Expected Behavior

this should be highlighted in the pulumi-cloudflare release log

### Steps to reproduce

use ArgoTunnel, upgrade to v5

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @omercnet , thanks for opening this issue and apologies for the lack of sufficient release notes. We've filed an issue to try and improve on our process [here](https://github.com/pulumi/schema-tools/issues/24).
