### ISSUE TITLE
Code examples no longer being included

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-cloudflare#40]
This may be a more general https://github.com/pulumi/pulumi-terraform-bridge issue, but I noticed it here first.

In #39 the code snippets were removed (e.g. https://github.com/pulumi/pulumi-cloudflare/commit/6b27274e577883691010c24a610868d2cf7c9ee2#diff-54e866f926ca8c6e87f7fdee3af014dcL14)

Why?

**Comment by pgavlin** [comment]
I expect this may be a TF12 issue.

**Comment by stack72** [comment]
Covered by https://github.com/pulumi/tf2pulumi/issues/136
