### ISSUE TITLE
Version v5.1.0 provides an empty version to engine

### ISSUE THREAD

**Issue by spigell** [pulumi/pulumi-cloudflare#403]
### What happened?

The latest version of the plugin (5.1.0) is unusable because the engine doesn't accept an empty version.
```
error: fatal: failed to Init GRPC to register RPC handlers: failed to create resource provider: ProviderInfo needs a semver-compatible version string, got info.Version
error: could not read plugin [/home/spigell/.pulumi/plugins/resource-cloudflare-v5.1.0/pulumi-resource-cloudflare] stdout: EOF
```

### Expected Behavior

The plugin works

### Steps to reproduce
```
[spigell@dragonfish gcp ]$ pulumi plugin install resource cloudflare v5.1.0
[resource plugin cloudflare-5.1.0] installing
Downloading plugin: 19.98 MiB / 19.98 MiB [=========================] 100.00% 3s
[spigell@dragonfish gcp ]$ /home/spigell/.pulumi/plugins/resource-cloudflare-v5.1.0/pulumi-resource-cloudflare -version
<empty>
```

### Output of pulumi about
````
Backend        
Name           pulumi.com
URL            https://app.pulumi.com/spigell
User           spigell
Organizations  spigell, infraunlimited

Dependencies:
NAME                VERSION
@pulumi/cloudflare  5.1.0
@pulumi/gcp         6.52.0
@pulumi/pulumi      3.60.0
@types/node         16.18.22
lint-staged         13.2.0
mrm                 2.6.2
prettier            2.8.7
`````````
### Additional context

Works well for version 5.0.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thank you for reporting this! The ecosystem team is looking into this shortly, marked as P1.  In the meanwhile recommend downgrading to https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.0.0

**Comment by t0yv0** [comment]
Tagged v5.1.1 and it should be available shortly with a fix. Apologies for the disruption here! This regression should have been caught by our acceptance tests but they were being silently skipped. This is now fixed also.
