### ISSUE TITLE
Document how to provide cloudflare credentials

### ISSUE THREAD

**Issue by gobengo** [pulumi/pulumi-cloudflare#41]
There isn't really any documentation in the README on how to provide cloudflare credentials like apiToken, email, etc.

I looked in examples/worker/Pulumi.yaml, which mentions a `cloudflare:token` Pulumi config. But when I provided that and used with pulumi-cloudflare 1.0.0, I got an error that it was an unknown config key.

I searched the codebase and found [vars.ts](https://github.com/pulumi/pulumi-cloudflare/blob/2f5bfa1a029ef7a3644bee421bd45b85dc6905b1/sdk/nodejs/config/vars.ts) that seems to refer to `cloudflare:apiToken` config, and I also notice it checks for environment variables, which is how I'd prefer to pass this anyway.

So I found this. But it sounds like:
* The example in the repo should be updated to not use `cloudflare:token` since it doesn't work with 1.0.0
* The README should mention how to provide cloudflare credentials

**Comment by stack72** [comment]
Hi @gobengo 

Apologies for the lack of information here - I just opened #42 that will help with this

I also added tests that will run on each PR and you can see what the tests do via the travis build

Hope it helps

Paul
