### ISSUE TITLE
Custom Rules sometimes missing parameters

### ISSUE THREAD

**Issue by VitoSantos22** [pulumi/pulumi-cloudflare#426]
### What happened?

When we create custom rules with "Skip" action via pulumi sometimes it create the rule without the skip phase `All remaining custom rules `inside `action_parameters`. This paremeters it's not an explicit phases, and saw the behaviour of the others rules who are created with these field, i can understand it's a default parameters

### Expected Behavior

Every rules created inside the cycle must have a `All remaining custom rules` enabled

### Steps to reproduce

I not understand how i can reproduce that, because in the same cycle randomly someone skip this parameters

### Output of `pulumi about`

CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @VitoSantos22, I see you closed this. Were you able to determine what the issue was?

**Comment by VitoSantos22** [comment]
Hi @AaronFriel, i've missed "ruleset: current" in some action_parameters.
No code issue.
