### ISSUE TITLE
Configurable user-agent

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-cloudflare#514]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The work has been done here:
https://github.com/cloudflare/terraform-provider-cloudflare/pull/2816

Consider adopting this as a patch.

**Comment by mikhailshilkov** [comment]
Dupe of https://github.com/pulumi/pulumi-cloudflare/issues/179
