### ISSUE TITLE
accountId missing from config schema

### ISSUE THREAD

**Issue by shaunco** [pulumi/pulumi-cloudflare#579]
### What happened?

 error: pulumi:providers:cloudflare resource 'default_5_16_0' has a problem: could not validate provider configuration: Invalid or unknown key. Check `pulumi config get cloudflare:accountId`.

### Example

The README for this repo (and the docs on Pulumi) show that config can optionally contain `cloudflare:accountId`, which worked great in v4 and was accessible through `cloudflare.config.accountId`, but is gone in v5, as the schema no longer includes it:

https://github.com/pulumi/pulumi-cloudflare/blob/ac85abc72cec78313e6fb2f61559d9b53fbb3fe6/provider/cmd/pulumi-resource-cloudflare/schema.json#L54-L135

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @shaunco. Thanks for pointing this out!

**Comment by Sandy-Garrido** [comment]
Hey!
Interesting that no one has mentioned this in any of the open issues.
I see you've removed it from the docs, which is great, however I've today first time using pulumi and installing the latest version for node.
but I am getting an error when accountId is missing

```
error: Missing required configuration variable 'cloudflare:accountId'
please set a value using the command `pulumi config set cloudflare:accountId <value>`
```

but setting it causes a configuration issue as it doesn't like it

```
error: pulumi:providers:cloudflare resource 'default_5_41_0' has a problem: 
`cloudflare:accountId` is not a valid configuration key for the cloudflare provider. 
If the referenced key is not intended for the provider, please choose a different namespace from `cloudflare:`
```

Does this mean it's impossible to use cloudflare with Pulumi right now?

ps. I'm using `pulumi preview` command when I get this. Not tried anything else
