### ISSUE TITLE
Ability to create Custom Hostnames

### ISSUE THREAD

**Issue by cdloh** [pulumi/pulumi-cloudflare#65]
SSL for SaaS has Custom hostnames which can be applied to a zone - https://support.cloudflare.com/hc/en-us/articles/217371987-Managing-Custom-Hostnames-SSL-for-SaaS-

Can we get the ability to create and manage these?

**Comment by leezen** [comment]
Upstream tracking issue: https://github.com/terraform-providers/terraform-provider-cloudflare/issues/336

**Comment by stack72** [comment]
Closed in the v2.5.0 release of the provider - apologies for not circling back on this earlier!
