### ISSUE TITLE
Incorrect description for `module` in API docs

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi-cloudflare#661]
### What happened?

I have a WorkerScript.content that points to a local js file, and the js file contains import statements. However, Pulumi does not currently allow to upload these successfully.

```bash
     * error updating worker script: Uncaught SyntaxError: Cannot use import statement outside a module
```

### Example

Here's an [example of a WorkerScript file with import statements](https://developers.cloudflare.com/workers-ai/models/text-to-image/#examples).

If we store the above example in an `app.js` file to define in a `WorkerScript` resource:

```typescript
const script = new cloudflare.WorkerScript("test" + DEMOFLAG, {
  accountId: accountId,
  name: "test" + DEMOFLAG,
  content: fs.readFileSync("app.js", "utf8"),

});
```
 fails with the above error.

### Output of `pulumi about`

```bash
CLI          
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
cloudflare  5.21.0
nodejs      unknown

Host     
OS       darwin
Version  14.3
Arch     arm64


```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @desteves. Have you tried setting `module` to true?

```ts
const script = new cloudflare.WorkerScript("test" + DEMOFLAG, {
  accountId: accountId,
  name: "test" + DEMOFLAG,
  content: fs.readFileSync("app.js", "utf8"),
  module: true,
});
```

That should enable "ES Module syntax" for the script.

**Comment by desteves** [comment]
Thank you, @iwahbe. I'm giving that a try. I overlooked that setting due to its description -- "The base64 encoded wasm module you want to store."

**Comment by iwahbe** [comment]
That description is wrong. We're working on our description generation process, but it's not perfect right now.

**Comment by iwahbe** [comment]
Great. I'm going to leave this issue open as a tracker for the incorrect docs.
