### ISSUE TITLE
Ruleset property descriptions are messed up

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-cloudflare#700]
### What happened?

A few descriptions of Ruleset's properties look to be applied out of place. 

For. example `name` should be `Name of the ruleset.` ([TF schema](https://github.com/cloudflare/terraform-provider-cloudflare/blob/bf146186813ead27c49e61df587d32a383d72360/internal/framework/service/rulesets/schema.go#L66), [TF docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#name)) but it's `Name of the compression algorithm to use. Available values: gzip, brotli, auto, default, none` ([Pulumi schema](https://github.com/pulumi/pulumi-cloudflare/blob/1b5e3ce3fce91264e1ecff1582f336f47b8d28f2/provider/cmd/pulumi-resource-cloudflare/schema.json#L18273), [Pulumi docs](https://www.pulumi.com/registry/packages/cloudflare/api-docs/ruleset/#inputs)):
<img width="739" alt="image" src="https://github.com/pulumi/pulumi-cloudflare/assets/1454008/9650443a-498c-4b74-8284-9e22bb2dfc7c">

`rules` is wrong too:
<img width="747" alt="image" src="https://github.com/pulumi/pulumi-cloudflare/assets/1454008/e4085128-9341-4198-8218-f2f838e45df3">

### Example

See above

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I digged into this a little bit. The `name` description seems to be defined perfectly well in the docs: https://github.com/cloudflare/terraform-provider-cloudflare/blob/bf146186813ead27c49e61df587d32a383d72360/docs/resources/ruleset.md?plain=1#L442

When we parse these docs in TF bridge, we parse `name` and its siblings as `Attributes` in our nomenclature, not `Arguments`.

Then, we make a wrong choise in this block: https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/generate.go#L1855-L1884

A `name` argument exists somewhere down in the hierarchy of arguments (in `rules/actionParameters/algorithms/name`) and we take that name and return it as the top-level `name`'s doc (wrong). We never get to iterating attributes, so the proper description is lost.

Now, the comment strongly suggests that the priority of arguments vs. attributes is by design. Does it mean that our parsing of arguments goes wrong?

cc @iwahbe Who touched it all in #1398

**Comment by iwahbe** [comment]
Related to https://github.com/pulumi/pulumi-terraform-bridge/issues/1789, CC @guineveresaenger

**Comment by guineveresaenger** [comment]
Fixed via https://github.com/pulumi/pulumi-terraform-bridge/pull/1882.
