### ISSUE TITLE
[Go] Cloudflare resource name argument is a string. Can't be dynamic

### ISSUE THREAD

**Issue by Mokto** [pulumi/pulumi-cloudflare#72]
Hey,

Disclaimer: I'm trying to migrate from Typescript to Golang one of my Pulumi project, for fun. I'm not really good in Golang so I might miss something.

I would like to build a dynamic string for the resource name with "Apply"
```
resourceName := pulumi.All(zoneID.ToStringOutput(), name).ApplyT(func(args []interface{}) string {
	zoneID := args[0].(string)
	name := args[1].(string)
	return fmt.Sprintf("%s/%s", zoneID, name)
})
```

```
cloudflare.NewRecord(ctx, resourceName, &cloudflare.RecordArgs{
	Name:   pulumi.String(name),
	ZoneId: pulumi.String(zoneID),
	Type:   pulumi.String("A"),
	Value:  c.serviceStack.GetStringOutput(pulumi.String("externalIp")),
	Ttl:    pulumi.Int(1),
})
```

But it doesn't work because resourceName has to be a string.

Is there any way around it ?

Thanks.

**Comment by leezen** [comment]
In general, we don't recommend using `Output`s to name resources. The name of the resource must be 'known' when we create it, so it should not rely on an `Output` (this is true across all languages). While you could create the resource within the `apply` there are a lot of issues with doing that (see https://www.pulumi.com/docs/intro/concepts/programming-model/#apply) and it's not recommended.
