### ISSUE TITLE
MX DNS Records always show diff with deletion of "data" since today/yesterday

### ISSUE THREAD

**Issue by skirsten** [pulumi/pulumi-cloudflare#902]
### Describe what happened

I guess since sometime today or yesterday the API response change and now MX records always show a diff.

### Sample program

```yaml
name: repro-mx-record-broken
runtime: yaml
resources:
  provider:
    type: pulumi:providers:cloudflare
    defaultProvider: true
    options:
      version: 5.38.0
  test:
    type: cloudflare:Record
    properties:
      zoneId: ZONE_ID_HERE
      type: MX
      name: test
      content: example.com
      priority: 1
```

Then run `pulumi up` the first time, everything is good.

On all `pulumi up` after that it will always show a diff on the MX record:

### Log output

```
~ cloudflare:index/record:Record: (update)
    [id=c5442369babaeb651b48372caef6a7a6]
    [urn=urn:pulumi:main::repro-mx-record-broken::cloudflare:index/record:Record::test]
    [provider=urn:pulumi:main::repro-mx-record-broken::pulumi:providers:cloudflare::provider::daa91236-95fd-406f-b193-d43ab45e3340]
  - data: {
      - algorithm    : 0
      - altitude     : 0
      - certificate  : ""
      - content      : ""
      - digest       : ""
      - digestType   : 0
      - fingerprint  : ""
      - flags        : ""
      - keyTag       : 0
      - latDegrees   : 0
      - latDirection : ""
      - latMinutes   : 0
      - latSeconds   : 0
      - longDegrees  : 0
      - longDirection: ""
      - longMinutes  : 0
      - longSeconds  : 0
      - matchingType : 0
      - name         : ""
      - order        : 0
      - port         : 0
      - precisionHorz: 0
      - precisionVert: 0
      - preference   : 0
      - priority     : 1
      - proto        : ""
      - protocol     : 0
      - publicKey    : ""
      - regex        : ""
      - replacement  : ""
      - selector     : 0
      - service      : ""
      - size         : 0
      - tag          : ""
      - target       : "example.com"
      - type         : 0
      - usage        : 0
      - value        : ""
      - weight       : 0
    }
  - data: {
      - algorithm    : 0
      - altitude     : 0
      - certificate  : ""
      - content      : ""
      - digest       : ""
      - digestType   : 0
      - fingerprint  : ""
      - flags        : ""
      - keyTag       : 0
      - latDegrees   : 0
      - latDirection : ""
      - latMinutes   : 0
      - latSeconds   : 0
      - longDegrees  : 0
      - longDirection: ""
      - longMinutes  : 0
      - longSeconds  : 0
      - matchingType : 0
      - name         : ""
      - order        : 0
      - port         : 0
      - precisionHorz: 0
      - precisionVert: 0
      - preference   : 0
      - priority     : 1
      - proto        : ""
      - protocol     : 0
      - publicKey    : ""
      - regex        : ""
      - replacement  : ""
      - selector     : 0
      - service      : ""
      - size         : 0
      - tag          : ""
      - target       : "example.com"
      - type         : 0
      - usage        : 0
      - value        : ""
      - weight       : 0
    }
```

### Affected Resource(s)

cloudflare:Record

### Output of `pulumi about`

CLI          
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  5.38.0
language  yaml        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/skirsten
User           skirsten
Organizations  skirsten
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @skirsten - thank you for filing this issue.

Could it be that you were running into [this Cloudflare incident](https://www.cloudflarestatus.com/incidents/79h1kvybmthk)?

It seems that [upstream users were running into a similar issue](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3965) on MX records with the `data` field.

Could you verify this issue still persists? My hope is that this has been resolved entirely.
If you still see a diff, you could try a `pulumi refresh` to reconcile your state with the cloud state.

**Comment by skirsten** [comment]
Hi,
I just checked and yes, the issue is resolved now.

Thanks for pointing me to the incident. I guess I overlooked it or it did not exist yet when I created the issue.
