### ISSUE TITLE
Missing storage class in R2 bucket

### ISSUE THREAD

**Issue by hckhanh** [pulumi/pulumi-cloudflare#932]
### Describe what happened

It lacks the storage class for R2 bucket: https://www.pulumi.com/registry/packages/cloudflare/api-docs/r2bucket/#inputs

You can read more about it here: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/r2_bucket#storage_class

### Sample program

You can check the docs, I don't think it need to have a sample code

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @hckhanh. If you look at the version of the Terraform registry link you sent, you will see it is v5.0.0-alpha. pulumi-cloudflare targets the latest stable version of terraform-provider-cloudflare: v4.43.0.

As soon as terraform-provider-cloudflare v5.0.0 is published, we will adopt it.
