### ISSUE TITLE
Hyperdrive - Node.js - Wrong ID output

### ISSUE THREAD

**Issue by andresusanto** [pulumi/pulumi-cloudflare#961]
### Describe what happened

Creating a `HyperdriveConfig` resource and getting its ID from the output will return the cloudflare Zone ID instead of the Hyperdrive ID.

### Sample program

```ts
export const hyperDrive = new HyperdriveConfig('hyperdrive', {
  accountId: 'account',
  name: 'somename',
  origin: {
    scheme: 'postgres',
    user: 'user',
    password: 'password',
    host: 'host',
    database: 'dbName',
    port: 5432,
  },
});

hyperDrive.id // <-- this will return the same value as hyperDrive.accountId
hyperDrive.accountId // <-- this will return the same value as hyperDrive.id
```

### Affected Resource(s)

HyperdriveConfig

### Output of `pulumi about`

```
CLI
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME                VERSION
resource  cloudflare          5.42.0
resource  gcp                 8.0.0
language  nodejs              unknown
resource  std                 1.7.3
resource  terraform-provider  0.3.0

Host
OS       darwin
Version  15.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @andresusanto thanks for reporting and sorry you've hit this. We currently have no workaround for this but I've raised https://github.com/pulumi/pulumi-terraform-bridge/issues/2612 for root-cause of the issue and will add a fix for this resource.

**Comment by andresusanto** [comment]
Thank you for looking and fixing this @VenelinMartinov!

**Comment by VenelinMartinov** [comment]
@andresusanto the resource id should be available under `resourceId` - unfortunately the `id` property has to be mapped to something else because the resource allows the hyper drive id to be set by the user and the pulumi engine does not accept that.
